title: "BK Conference Deadlines"
description: "Brain Korea (BK Lists) conference submission deadlines"
url: "https://joonsooyoo.github.io"
baseurl: "/bk-deadlines"   # Only if you plan to name the repo something like bk-deadlines

